version: 2.1
orbs:
    node: circleci/node@1.0.0
jobs:
    build-and-test:
        working_directory: ~/ProyectoFinalNode
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - setup_remote_docker
            - add_ssh_keys
            - run:
                name: Set Up Docker Command
                command: |
                    if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
                        echo "export docker='sudo docker'" >> $BASH_ENV
                    else
                        echo "export docker='docker'" >> $BASH_ENV
                    fi          
            - run: 
                name: Testing
                command: npm install     
workflows:
    build-and-test:
        jobs:
            - build-and-test
