version: 2
orbs:
    node: circleci/node@1.0.0 
jobs:
    build:
        docker:
            - image: circleci/node:latest
        evironment:
            - IMAGE_NAME: 'mdlfvan/proyectofinal'
        steps: 
            - checkout
            - setup_remote_docker
            - add_ssh_keys
            - run:
                name: Set Up Docker Command
                command: |
                    if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
                        echo "export docker='sudo docker'" >> $BASH_ENV
                    else
                        echo "export docker='docker'" >> $BASH_ENV
                    fi
            - run:
                name: Build Images
                command: |
                    $docker-compose -f docker-compose.desarrollo.yml build
                    $docker-compose -f docker-compose.yml build


