version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        working_directory: ~/ProyectoFinalNode
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - setup_remote_docker
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - run: 
                name: Testing
                command: npm run test
            - run:
                name: ejecucion
                command: node src
workflows:
    build-and-test:
        jobs:
            - build-and-test
