version: 2.1
jobs:
    build-and-test:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - setup_remote_docker
            - run: Install npm dependencies
            - run:
                name: update-npm
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
workflows:
    build-and-test:
        jobs:
            - build-and-test
