version: 2
jobs:
  build:
    docker: 
    - image: circleci/node:4.8.2
    working_directory: ~/repo
      steps:
        - checkout 
        - run: npm install -g nodemon
        - run: npm install
        - save_cache: 
          key: npm-cache-{{.Branch}}-{{checksum "package.json"}}
          path:
            - node_modules
workflows:
jobs:
- run_test 