vversion: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  run_test:
    docker:
        - image: circleci/node:carbon-alpine
    steps:
      - checkout      
        steps:
          - run: npm install
workflows:
    build-and-test:
      jobs:
        - run_test