version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      build:
        docker:
        - image: circleci/node:latest

      working_directory: ~/project

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install
            - restore_cache:
              keys: 
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies
      
            - run: install dependencies
      
            - save_cache:
              paths:
              - ./node_modules
              key: v1-dependencies-{{ checksum "package.json" }}
      
            - run:
              name: Testing
              command: node src
workflows:
  build-and-test:
    jobs:
      - build-and-test
