version: 2.1

orbs:
  node: circleci/node@8.10.0
jobs:
  run_test:
    build:
      docker: 
      - image: mdflvan/proyectofinal
      steps:
        - checkout 
        - run: npm install -g nodemon
        - run: npm install
        - run: 
          name: Run Unit test_results
          command: |
            ./node_module/nodemon/bin/nodemonsrc dev
        - store_test_results:
          path: test_results
workflows:
  version: 2
  workflow:
    jobs:
    - run_test 
    - build
