version: 2.1
orbs:
  node: circleci/node@8.10.0
jobs:
  run_test:
    build:
      docker: 
      - image: node:carbon-alpine
      steps:
        - checkout 
        - run: npm install -g nodemon
        - run: npm install
        - run: 
          name: Run Unit test_results
          command: |
            ./node_module/nodemon/bin/nodemonsrc dev
        - store_test_results:
          path: test_results
workflows:
  build-and-test:
    jobs:
    - run_test 
