vversion: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  run_test:
    executor:
      docker:
          - image: circleci/node:carbon-alpine
      steps:
        - checkout      
          steps:
            - run: npm install
            - run:
              name: Make
              command: node src
workflows:
    run_test:
      jobs:
        - run_test