version: 2.1
jobs:
  build-and-test:
    docker: 
      - image: circleci/node:carbon-alpine
    steps:
      - checkout
        steps:
          - run: npm install
          - run: npm install dependencies
workflows:
    build-and-test:
      jobs:
        - build-and-test