version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:carbon-alpine
    steps:
      - checkout 
      run: 
        name: npm install dependencies
        command: |
          npm install --save
      - run:
        name: Run Unit Tests
