
version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest

    working_directory: ~/repo

    steps:
    - checkout

      - restore_cache:
        keys: 
        - v1-dependency-{{ checksum "package.json" }}
        - v1-dependencies

      - run: yarn install

      - save_cache:
        paths:
        - ./node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: Testing
        command: npm run dev

workflows:
  version: 2
  build:
    jobs:
      - build