version: 2.0

orbs:
  node: circleci/node@8.10.0
jobs:
  run_test:
    docker: 
    - image: mdflvan/proyectofinal:latest
    working_directory: ~/repo
      steps:
        - checkout 
        - run: npm install -g nodemon
        - run: npm install
        - store_test_results:
          path: test_results
workflows:
  version: 2
  workflow:
    jobs:
    - run_test 