version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:carbon-alpine
    steps:
      - checkout 
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json"}}
          -v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{ { checksum "package.json"}}
      - setup_remote_docker:
          docker_layer_caching: true
      run: 
        name: npm install dependencies
        command: |
          npm install --save
      - run:
        name: Run Unit Tests
