version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      build:
        docker:
        - image: circleci/node:latest

      working_directory: ~/project

    steps:
      - checkout

      - node/with-cache:
          steps:            
            - run:
              name: update-npm
              command: 'sudo npm install -g npm@latest'

            - restore_cache:
              keys: 
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies
      
            - run: install dependencies
      
            - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
              - ./node_modules
      
            - run:
              name: Testing
              command: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
