version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        executor:
            name: node/default
        build:
            docker:
                - image: circleci/node:latest

        steps:
            - checkout
            - run: 
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
            - node/with-cache:
            steps: 
                - run: install dependencies
                - run:
                name: update-npm
                command: 'sudo npm install -g npm@latest'
                - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                - ./node_modules
                - run: 
                    name: test
                    command: node src
                - run: |
                if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
                echo "It worked!";
                else
                echo "Nope!"; exit 1
                fi
workflows:
    build-and-test:
        jobs:
            - build-and-test
