version: 2.1
jobs:
  run_tests:
    docker: 
      - image: circleci/node:carbon-alpine
    steps:
      - checkout
        steps:
          - run: npm install
        - run:
          - name: npm install dependencies
          command: |
            npm install --save
          - run:
            name: Run Unit Tests
workflows:
  build-and-test:
    jobs:
      - run_tests