version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        executor:
            name: node/default
        build:
            docker:
                - image: circleci/node:latest

        steps:
            - checkout
            - run: 
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}

            steps: 
                - run: 
                    name: install dependencies
                    command: |
                    npm install --save
                - run:
                    name: update-npm
                    command: 'sudo npm install -g npm@latest'
               - run:
                    name: Run Unit Tests
                    command: |
                    ./node_modules
                - run: 
                    name: test
                    command: npm dev
                - run: |
                if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
                echo "It worked!";
                else
                echo "Nope!"; exit 1
                fi
workflows:
    build-and-test:
        jobs:
            - build-and-test
